import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "AI Studio — AI-системы, продукты и автоматизации",
  description: "AI Studio от AI Skill Lab: research systems, AI products, websites, automation и team enablement с human gates, QA и понятным handoff.",
  alternates: { canonical: "/studio", languages: { ru: "/studio", en: "/en/studio" } },
};

const offers = [
  ["01", "AI PRODUCT / WEBSITE", "От идеи и messy requirements до работающего prototype или AI-ready web product.", "SPEC → UI / CODE → QA → HANDOFF"],
  ["02", "RESEARCH / DECISION", "Системы, которые собирают источники, сравнивают версии и превращают шум в reviewable decision brief.", "SOURCES → SYNTHESIS → HUMAN JUDGEMENT"],
  ["03", "AUTOMATION / AGENT", "Повторяемый workflow с bounded AI role, permissions, fallback, test cases и понятным owner.", "PROCESS → AGENT / FLOW → FALLBACK"],
  ["04", "TEAM ENABLEMENT", "Настраиваем рабочую AI-систему и одновременно передаём команде способность пользоваться, проверять и развивать её.", "SYSTEM → TRAIN → TRANSFER"],
] as const;

export default function StudioPage(){return <><Header alternateHref="/en/studio"/><main id="main" className="proofPage">
  <section className="proofHero"><div className="shell proofHeroGrid"><div><span className="proofEyebrow"><i/> AI STUDIO / BUILD WITH US</span><h1>Не только учиться.<br/><em>Можно собрать вместе.</em></h1><p>AI Skill Lab работает и как build studio: продукт, research-system, automation или внутренний AI-workflow. AI ускоряет сборку; человек остаётся владельцем цели, критериев, риска и финального решения.</p><div className="heroActions"><Link className="button buttonLight" href="/start">Обсудить задачу →</Link><Link className="button buttonGhost buttonOnDark" href="/proof">Проверить наш метод →</Link></div></div><div className="proofConsole" aria-label="AI Studio delivery console"><div className="proofConsoleTop"><span>AI SKILL LAB / DELIVERY MODEL</span><b>● CUSTOM SCOPE</b></div><div className="proofConsoleBody"><p><span>01</span><b>goal</b><strong>DEFINED</strong></p><p><span>02</span><b>ai_role</b><strong>BOUNDED</strong></p><p><span>03</span><b>human_gate</b><strong>OWNED</strong></p><p><span>04</span><b>artifact</b><strong>SHIPPABLE</strong></p><p><span>05</span><b>failure_mode</b><strong>KNOWN</strong></p><p><span>06</span><b>handoff</b><strong>REVIEWABLE</strong></p></div><div className="proofConsoleFoot"><span>DIAGNOSE</span><i/><span>BUILD</span><i/><span>VERIFY</span><i/><span>TRANSFER</span></div></div></div></section>

  <section className="section" id="studio-offers"><div className="shell"><nav className="heroActions" aria-label="Навигация AI Studio"><Link className="textLink" href="#studio-offers">Что строим</Link><Link className="textLink" href="#studio-delivery">Как работаем</Link><Link className="textLink" href="#studio-fit">Когда подходит</Link><Link className="textLink" href="#studio-claims">Ограничения</Link><Link className="textLink" href="#studio-brief">Дать задачу</Link></nav><div className="sectionHead splitHead"><div><span className="kicker">What we build</span><h2>Четыре типа<br/><em>практической AI-работы.</em></h2></div><p>Не продаём «AI ради AI». Выбираем форму по задаче и заранее определяем, что именно должно остаться после работы.</p></div><div className="programGrid">{offers.map(([i,t,x,ship])=><article className="programCard" key={t}><span className="cardIndex">{i}</span><div className="cardSpacer"/><span className="cardMeta">CUSTOM SCOPE</span><h3>{t}</h3><p>{x}</p><p><strong>{ship}</strong></p></article>)}</div></div></section>

  <section className="section sectionInk" id="studio-delivery"><div className="shell"><div className="sectionHead splitHead sectionHeadLight"><div><span className="kicker kickerLight">Delivery loop</span><h2>Работа заканчивается<br/><em>не demo, а handoff.</em></h2></div><p>Сначала ограничиваем задачу. Потом собираем минимально достаточную систему, ломаем её тестами и передаём с понятными operating boundaries.</p></div><div className="proofGateGrid"><article><span>01</span><h3>DIAGNOSE</h3><p>Цель, текущий процесс, данные, owner и ограничения.</p></article><article><span>02</span><h3>SCOPE</h3><p>Что AI делает, что не делает, какой artifact считается готовым.</p></article><article><span>03</span><h3>BUILD</h3><p>Prototype / workflow / system с минимальной полезной сложностью.</p></article><article><span>04</span><h3>VERIFY</h3><p>Sources, edge cases, failure modes, privacy, QA и human review.</p></article><article><span>05</span><h3>SHIP</h3><p>Рабочий artifact + known limits + release/readiness evidence.</p></article><article><span>06</span><h3>TRANSFER</h3><p>Handoff, operating instructions и способность продолжить без зависимости от «магии» исполнителя.</p></article></div></div></section>

  <section className="proofSplit" id="studio-fit"><div className="shell proofSplitGrid"><article><span className="kicker">Хороший кандидат</span><h2>AI есть зачем<br/>подключать.</h2><ul><li>много ручного поиска или повторяющихся шагов</li><li>нужен быстрый prototype перед большой разработкой</li><li>есть документы / знания, которые сложно использовать</li><li>команда хочет системный AI-workflow, а не набор промптов</li></ul></article><article className="proofHuman"><span className="kicker kickerLight">Stop conditions</span><h2>Иногда AI<br/>вообще не нужен.</h2><ul><li>нет владельца процесса и критериев качества</li><li>стоимость проверки выше пользы автоматизации</li><li>задача требует недопустимой автономности или доступа</li><li>обычный deterministic software решает проблему проще</li></ul></article></div></section>

  <section className="section" id="studio-claims"><div className="shell proofHonesty"><div><span className="kicker">Claims discipline</span><h2>Чего AI Studio<br/><em>не обещает.</em></h2></div><div><p>Нет гарантированного ROI, «замены сотрудников», безошибочной модели или автономного решения критичных бизнес-вопросов без владельца.</p><p>Есть другое: ограниченный scope, работающий artifact, явная проверка, известные limits и решение <strong>Ship / Revise / Stop</strong>.</p><div className="heroActions"><Link className="button buttonPrimary" href="/start">Дать задачу →</Link><Link className="textLink" href="/build">Как мы построили этот сайт →</Link></div></div></div></section>

  <section className="contactSection" id="studio-brief"><div className="shell contactGrid"><div><span className="kicker kickerLight">First brief</span><h2>Достаточно описать<br/>одну реальную проблему.</h2><p>Что сейчас происходит вручную, что хочется получить и где ошибка будет стоить дорого. Инструменты и архитектуру подберём после диагностики.</p><div className="heroActions"><Link className="button buttonLight" href="/start">Открыть Start →</Link><Link className="button buttonGhost buttonOnDark" href="/projects">Project Studio →</Link></div></div><div className="proofMiniCard"><span>STUDIO LOOP</span><strong>DIAGNOSE<br/>BUILD<br/>VERIFY<br/><em>TRANSFER</em></strong><small>Human owns release.</small></div></div></section>
</main><Footer/></>}
