import type { Metadata } from "next";
import { WorkshopEditorial } from "@/components/workshop/WorkshopEditorial";
import Link from "next/link";
export const metadata: Metadata = {
  title: { absolute: "AI Studio: проекты с ИИ — AI Skill Lab · Пхукет" },
  description: "AI Studio от AI Skill Lab: research systems, AI products, websites, automation и team enablement с human gates, QA и понятным handoff.",
  alternates: { canonical: "/studio", languages: { ru: "/studio", en: "/en/studio" } },
};

const offers = [
  ["01", "ИИ-ПРОДУКТ / САЙТ", "От идеи и неструктурированных требований до работающего прототипа или веб-продукта с ИИ.", "СПЕЦИФИКАЦИЯ → UI / КОД → QA → ПЕРЕДАЧА"],
  ["02", "ИССЛЕДОВАНИЕ / РЕШЕНИЕ", "Системы, которые собирают источники, сравнивают версии и превращают шум в проверяемое краткое решение.", "ИСТОЧНИКИ → SYNTHESIS → ЧЕЛОВЕК JUDGEMENT"],
  ["03", "АВТОМАТИЗАЦИЯ / АГЕНТ", "Повторяемый рабочий процесс с ограниченной ролью ИИ, разрешениями, запасным вариантом, тестовыми случаями и назначенным владельцем.", "ПРОЦЕСС → АГЕНТ / FLOW → ЗАПАСНОЙ ВАРИАНТ"],
  ["04", "ОБУЧЕНИЕ КОМАНДЫ", "Настраиваем рабочую ИИ-систему и одновременно передаём команде способность пользоваться, проверять и развивать её.", "СИСТЕМА → TRAIN → ПЕРЕДАЧА"],
] as const;

export default function StudioPage(){return <WorkshopEditorial locale="ru" alternateHref="/en/studio"><main id="main" className="proofPage">
  <section className="proofHero"><div className="shell proofHeroGrid"><div><span className="proofEyebrow"><i/> СТУДИЯ / СОБИРАЕМ ВМЕСТЕ</span><h1>Не только учиться.<br/><em>Можно собрать вместе.</em></h1><p>AI Skill Lab работает и как студия ИИ-проектов: продукт, исследовательская система, автоматизация или внутренний рабочий процесс с ИИ. ИИ ускоряет сборку; человек остаётся владельцем цели, критериев, риска и финального решения.</p><div className="heroActions"><Link className="button buttonLight" href="/start#studio-brief">Обсудить задачу →</Link><Link className="button buttonGhost buttonOnDark" href="/proof">Проверить наш метод →</Link></div></div><div className="proofConsole" aria-label="AI Studio delivery console"><div className="proofConsoleTop"><span>AI SKILL LAB / DELIVERY MODEL</span><b className="statusDot">CUSTOM SCOPE</b></div><div className="proofConsoleBody"><p><span>01</span><b>goal</b><strong>DEFINED</strong></p><p><span>02</span><b>ai_role</b><strong>BOUNDED</strong></p><p><span>03</span><b>human_gate</b><strong>OWNED</strong></p><p><span>04</span><b>artifact</b><strong>SHIPPABLE</strong></p><p><span>05</span><b>failure_mode</b><strong>KNOWN</strong></p><p><span>06</span><b>handoff</b><strong>REVIEWABLE</strong></p></div><div className="proofConsoleFoot"><span>DIAGNOSE</span><i/><span>BUILD</span><i/><span>VERIFY</span><i/><span>TRANSFER</span></div></div></div></section>

  <section className="section" id="studio-offers"><div className="shell"><nav className="heroActions" aria-label="Навигация AI Studio"><Link className="textLink" href="#studio-offers">Что строим</Link><Link className="textLink" href="#studio-delivery">Как работаем</Link><Link className="textLink" href="#studio-fit">Когда подходит</Link><Link className="textLink" href="#studio-claims">Ограничения</Link><Link className="textLink" href="#studio-brief">Дать задачу</Link></nav><div className="sectionHead splitHead"><div><span className="kicker">Что мы создаём</span><h2>Четыре типа<br/><em>практической ИИ-работы.</em></h2></div><p>Не продаём «ИИ ради ИИ». Выбираем форму по задаче и заранее определяем, что именно должно остаться после работы.</p></div><div className="programGrid">{offers.map(([i,t,x,ship])=><article className="programCard" key={t}><span className="cardIndex">{i}</span><div className="cardSpacer"/><span className="cardMeta">ОБЪЁМ РАБОТ</span><h3>{t}</h3><p>{x}</p><p><strong>{ship}</strong></p></article>)}</div></div></section>

  <section className="section sectionInk" id="studio-delivery"><div className="shell"><div className="sectionHead splitHead sectionHeadLight"><div><span className="kicker kickerLight">ЦИКЛ РАБОТЫ</span><h2>Работа заканчивается<br/><em>не демонстрацией, а передачей результата.</em></h2></div><p>Сначала ограничиваем задачу. Потом собираем минимально достаточную систему, ломаем её тестами и передаём с понятными правилами работы и границами ответственности.</p></div><div className="proofGateGrid"><article><span>01</span><h3>ДИАГНОСТИКА</h3><p>Цель, текущий процесс, данные, владелец и ограничения.</p></article><article><span>02</span><h3>ОБЪЁМ РАБОТ</h3><p>Что ИИ делает, что не делает, какой результат считается готовым.</p></article><article><span>03</span><h3>СБОРКА</h3><p>Прототип / рабочий процесс / система с минимальной полезной сложностью.</p></article><article><span>04</span><h3>ПРОВЕРКА</h3><p>Источники, пограничные случаи, сценарии отказа, приватность, QA и проверка человеком.</p></article><article><span>05</span><h3>ЗАПУСК</h3><p>Работающий результат + известные ограничения + выпуск/readiness доказательства.</p></article><article><span>06</span><h3>ПЕРЕДАЧА</h3><p>Инструкции по работе, передача и способность продолжить без зависимости от «магии» исполнителя.</p></article></div></div></section>

  <section className="proofSplit" id="studio-fit"><div className="shell proofSplitGrid"><article><span className="kicker">Хороший кандидат</span><h2>Когда стоит<br/>подключать ИИ.</h2><ul><li>много ручного поиска или повторяющихся шагов</li><li>нужен быстрый прототип перед большой разработкой</li><li>есть документы / знания, которые сложно использовать</li><li>команда хочет системный рабочий процесс с ИИ, а не набор промптов</li></ul></article><article className="proofHuman"><span className="kicker kickerLight">УСЛОВИЯ ОСТАНОВКИ</span><h2>Иногда ИИ<br/>вообще не нужен.</h2><ul><li>нет владельца процесса и критериев качества</li><li>стоимость проверки выше пользы автоматизации</li><li>задача требует недопустимой автономности или доступа</li><li>обычное программное обеспечение решает проблему проще</li></ul></article></div></section>

  <section className="section" id="studio-claims"><div className="shell proofHonesty"><div><span className="kicker">ДИСЦИПЛИНА УТВЕРЖДЕНИЙ</span><h2>Чего Студия<br/><em>не обещает.</em></h2></div><div><p>Нет гарантированного ROI, «замены сотрудников», безошибочной модели или автономного решения критичных бизнес-вопросов без владельца.</p><p>Есть другое: ограниченный объём работ, работающий результат, явная проверка, известные ограничения и решение <strong>выпустить, доработать или остановить</strong>.</p><div className="heroActions"><Link className="button buttonPrimary" href="/start#studio-brief">Дать задачу →</Link><Link className="textLink" href="/build">Как мы построили этот сайт →</Link></div></div></div></section>

  <section className="contactSection" id="studio-brief"><div className="shell contactGrid"><div><span className="kicker kickerLight">Сначала короткое описание задачи</span><h2>Достаточно описать<br/>одну реальную проблему.</h2><p>Что сейчас происходит вручную, что хочется получить и где ошибка будет стоить дорого. Инструменты и архитектуру подберём после диагностики.</p><div className="heroActions"><Link className="button buttonLight" href="/start#studio-brief">Открыть заявку →</Link><Link className="button buttonGhost buttonOnDark" href="/projects">Примеры проектов →</Link></div></div><div className="proofMiniCard"><span>STUDIO ЦИКЛ</span><strong>ДИАГНОСТИКА<br/>СБОРКА<br/>ПРОВЕРКА<br/><em>ПЕРЕДАЧА</em></strong><small>Решение о выпуске принимает человек.</small></div></div></section>
</main></WorkshopEditorial>}
