import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "AI Studio — AI systems, products and automation",
  description: "AI Studio by AI Skill Lab: research systems, AI products, websites, automation and team enablement with human gates, QA and clear handoff.",
  alternates: { canonical: "/en/studio", languages: { ru: "/studio", en: "/en/studio" } },
};

const offers = [
  ["01", "AI PRODUCT / WEBSITE", "From an idea and messy requirements to a working prototype or AI-ready web product.", "SPEC → UI / CODE → QA → HANDOFF"],
  ["02", "RESEARCH / DECISION", "Systems that gather sources, compare versions and turn noise into a reviewable decision brief.", "SOURCES → SYNTHESIS → HUMAN JUDGEMENT"],
  ["03", "AUTOMATION / AGENT", "A repeatable workflow with a bounded AI role, permissions, fallback, test cases and a clear owner.", "PROCESS → AGENT / FLOW → FALLBACK"],
  ["04", "TEAM ENABLEMENT", "We set up a working AI system while transferring the team's ability to operate, verify and evolve it.", "SYSTEM → TRAIN → TRANSFER"],
] as const;

export default function StudioPage(){return <><Header locale="en" alternateHref="/studio"/><main id="main" className="proofPage">
  <section className="proofHero"><div className="shell proofHeroGrid"><div><span className="proofEyebrow"><i/> AI STUDIO / BUILD WITH US</span><h1>Not only learn.<br/><em>Build it with us.</em></h1><p>AI Skill Lab also works as a build studio: products, research systems, automation and internal AI workflows. AI accelerates the build; a human remains owner of the goal, criteria, risk and final release decision.</p><div className="heroActions"><Link className="button buttonLight" href="/en/start">Discuss a task →</Link><Link className="button buttonGhost buttonOnDark" href="/en/proof">Verify our method →</Link></div></div><div className="proofConsole" aria-label="AI Studio delivery console"><div className="proofConsoleTop"><span>AI SKILL LAB / DELIVERY MODEL</span><b>● CUSTOM SCOPE</b></div><div className="proofConsoleBody"><p><span>01</span><b>goal</b><strong>DEFINED</strong></p><p><span>02</span><b>ai_role</b><strong>BOUNDED</strong></p><p><span>03</span><b>human_gate</b><strong>OWNED</strong></p><p><span>04</span><b>artifact</b><strong>SHIPPABLE</strong></p><p><span>05</span><b>failure_mode</b><strong>KNOWN</strong></p><p><span>06</span><b>handoff</b><strong>REVIEWABLE</strong></p></div><div className="proofConsoleFoot"><span>DIAGNOSE</span><i/><span>BUILD</span><i/><span>VERIFY</span><i/><span>TRANSFER</span></div></div></div></section>

  <section className="section"><div className="shell"><div className="sectionHead splitHead"><div><span className="kicker">What we build</span><h2>Four kinds of<br/><em>practical AI work.</em></h2></div><p>We do not sell “AI for the sake of AI.” The shape follows the problem, and the shipped artifact is defined before the build expands.</p></div><div className="programGrid">{offers.map(([i,t,x,ship])=><article className="programCard" key={t}><span className="cardIndex">{i}</span><div className="cardSpacer"/><span className="cardMeta">CUSTOM SCOPE</span><h3>{t}</h3><p>{x}</p><p><strong>{ship}</strong></p></article>)}</div></div></section>

  <section className="section sectionInk"><div className="shell"><div className="sectionHead splitHead sectionHeadLight"><div><span className="kicker kickerLight">Delivery loop</span><h2>The work ends<br/><em>with a handoff, not a demo.</em></h2></div><p>We constrain the problem first, build the minimum useful system, break it with tests and transfer it with explicit operating boundaries.</p></div><div className="proofGateGrid"><article><span>01</span><h3>DIAGNOSE</h3><p>Goal, current process, data, owner and constraints.</p></article><article><span>02</span><h3>SCOPE</h3><p>What AI does, what it does not do and which artifact counts as done.</p></article><article><span>03</span><h3>BUILD</h3><p>Prototype / workflow / system with the minimum useful complexity.</p></article><article><span>04</span><h3>VERIFY</h3><p>Sources, edge cases, failure modes, privacy, QA and human review.</p></article><article><span>05</span><h3>SHIP</h3><p>Working artifact + known limits + release/readiness evidence.</p></article><article><span>06</span><h3>TRANSFER</h3><p>Handoff, operating instructions and the ability to continue without depending on an implementer&apos;s “magic.”</p></article></div></div></section>

  <section className="proofSplit"><div className="shell proofSplitGrid"><article><span className="kicker">Good candidate</span><h2>There is a reason<br/>to use AI.</h2><ul><li>too much manual research or repetitive work</li><li>a prototype is needed before a large build</li><li>documents / knowledge are hard to use</li><li>a team needs a governed AI workflow rather than a prompt collection</li></ul></article><article className="proofHuman"><span className="kicker kickerLight">Stop conditions</span><h2>Sometimes AI<br/>is the wrong answer.</h2><ul><li>there is no process owner or quality criteria</li><li>verification costs more than the automation saves</li><li>the task requires unacceptable autonomy or access</li><li>ordinary deterministic software solves it more simply</li></ul></article></div></section>

  <section className="section"><div className="shell proofHonesty"><div><span className="kicker">Claims discipline</span><h2>What AI Studio<br/><em>does not promise.</em></h2></div><div><p>No guaranteed ROI, “employee replacement,” infallible model or autonomous critical business decision without an owner.</p><p>What we do offer: bounded scope, a working artifact, explicit verification, known limits and a <strong>Ship / Revise / Stop</strong> decision.</p><div className="heroActions"><Link className="button buttonPrimary" href="/en/start">Bring a task →</Link><Link className="textLink" href="/en/build">How we built this site →</Link></div></div></div></section>

  <section className="contactSection"><div className="shell contactGrid"><div><span className="kicker kickerLight">First brief</span><h2>One real problem<br/>is enough to start.</h2><p>Describe what is manual today, what output you want and where a wrong result would be expensive. Tools and architecture come after diagnosis.</p><div className="heroActions"><Link className="button buttonLight" href="/en/start">Open Start →</Link><Link className="button buttonGhost buttonOnDark" href="/en/projects">Project Studio →</Link></div></div><div className="proofMiniCard"><span>STUDIO LOOP</span><strong>DIAGNOSE<br/>BUILD<br/>VERIFY<br/><em>TRANSFER</em></strong><small>Human owns release.</small></div></div></section>
</main><Footer locale="en"/></>}
