import type { Metadata } from "next";
import Link from "next/link";
import { ArrowIcon } from "@/components/ArrowIcon";
import { ContactButtons } from "@/components/ContactButtons";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";

export const metadata: Metadata = { title: "AI for kids ages 8–13", description: "One-to-one AI learning for ages 8–13 through creativity, research, verification, privacy and a final project.", alternates: { canonical: "/en/kids", languages: { ru: "/kids", en: "/en/kids" } } };

const lessons = [
  ["01","AI without magic","What AI can and cannot do, and why confident answers can still be wrong."],
  ["02","Better questions","Context, constraints and iterative improvement instead of one-shot prompts."],
  ["03","Visual worlds","Create characters, images and a coherent visual language for a project."],
  ["04","Story with AI","Plot, characters, logic and editing while keeping authorship with the child."],
  ["05","AI researcher","Find information, compare sources and separate facts from plausible invention."],
  ["06","Presentation","Turn a topic into a clear visual story that can be explained out loud."],
  ["07","Logic & algorithms","Break a task into steps and learn the beginnings of computational thinking."],
  ["08","Mini game","Build a small interactive project with rules, states and feedback."],
  ["09","My AI project","Plan the final work: goal, structure, materials, verification and improvement."],
  ["10","Demo day","Finish and present the project, explaining what was done independently and where AI helped."],
];

export default function EnglishKids() {
  return <><Header locale="en" contactHref="/en/start" alternateHref="/kids"/><main>
    <section className="kidsHero"><div className="shell kidsHeroGrid"><div><div className="eyebrow eyebrowLight"><span className="dot dotLight"/> Ages 8–13 · one-to-one</div><h1>AI is not a button<br/><span>that does it for you.</span></h1><p>It is a tool for imagining, researching, creating and learning to ask better questions — with verification and privacy built in.</p><div className="heroActions"><Link className="button buttonLight" href="/en/start">Talk about the program <ArrowIcon/></Link><Link className="textLink textLinkLight" href="#curriculum">See Creator curriculum <ArrowIcon/></Link></div></div><div className="kidsHeroBoard"><div className="boardLabel">FINAL PROJECT</div><div className="boardCanvas"><div className="boardCard bc1">IDEA<br/><b>→</b></div><div className="boardCard bc2">RESEARCH<br/><b>→</b></div><div className="boardCard bc3">CREATE<br/><b>→</b></div><div className="boardCenter">MY<br/>AI<br/>PROJECT</div></div><div className="boardFoot"><span>CREATOR CORE · 10 LESSONS</span><span>REAL OUTPUT</span></div></div></div></section>
    <section className="section"><div className="shell"><div className="sectionHead splitHead"><div><span className="kicker">Approach</span><h2>Build capability, not AI dependency</h2></div><p>The child learns to think before asking, verify after receiving an answer and understand the tool&apos;s boundaries.</p></div><div className="kidsPrinciples"><article><span>01</span><h3>Idea first</h3><p>The child starts with their own intent; AI helps develop it.</p></article><article><span>02</span><h3>Verification matters</h3><p>We examine errors and compare claims with reliable sources.</p></article><article><span>03</span><h3>Privacy by default</h3><p>No unnecessary personal information and clear digital boundaries.</p></article><article><span>04</span><h3>Project over prompt</h3><p>Progress means being able to design, build, explain and improve something.</p></article></div></div></section>
    <section className="section sectionMuted" id="curriculum"><div className="shell"><div className="sectionHead"><span className="kicker">Curriculum</span><h2>Creator: 10 sessions → one finished project</h2><p className="sectionSub">This is the Creator core. Mini selects the essential introduction plus a small project; Studio adds 2 sessions for deeper project work. Themes adapt to the learner&apos;s age and interests.</p></div><div className="curriculumList">{lessons.map(([n,t,x])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{x}</p></article>)}</div></div></section>
    <section className="section sectionMuted"><div className="shell"><div className="sectionHead splitHead"><div><span className="kicker">Pricing</span><h2>Choose the program depth</h2></div><p>One-to-one. Session duration, schedule and pace are agreed before payment for the learner, goal and format.</p></div><div className="pricingGrid"><article className="priceCard"><span className="cardMeta">Mini</span><h3>4 sessions</h3><div className="price">$290</div><p>A creative introduction and a small project.</p><Link className="button buttonGhost buttonWide" href="/en/start">Choose Mini</Link></article><article className="priceCard featuredPrice"><span className="popular">Core</span><span className="cardMeta">Creator</span><h3>10 sessions</h3><div className="price">$890</div><p>Full route from fundamentals to a self-presented final project.</p><Link className="button buttonPrimary buttonWide" href="/en/start">Choose Creator</Link></article><article className="priceCard"><span className="cardMeta">Studio</span><h3>12 sessions</h3><div className="price">$1,190</div><p>More time for visual work, a complex project or first technical experiments.</p><Link className="button buttonGhost buttonWide" href="/en/start">Choose Studio</Link></article></div></div></section>
    <section className="section safetyBand"><div className="shell safetyBandGrid"><div><span className="kicker">Age & safety</span><h2>Under 13: an adult stays in the loop.</h2></div><div><p>The program does not require an independent ChatGPT account for a child under 13. If ChatGPT is used as a demonstration tool, the actual interaction is conducted by an adult. Current age rules are checked before any AI service is used.</p><Link className="textLink" href="/en/safety">See youth AI safety rules <ArrowIcon/></Link></div></div></section>

    <section className="familyConciergeBand"><div className="shell familyConciergeGrid"><div><span className="kicker kickerLight">Family Concierge</span><h2>A higher-touch format for families.</h2><p>12 learner sessions + 2 parent sessions + custom project + home AI-use rules.</p></div><div className="familyConciergePrice"><span>PREMIUM</span><b>$1,490</b><Link className="button buttonLight buttonWide" href="/en/start">Discuss Family</Link></div></div></section>
    <section className="contactSection" id="kids-contact"><div className="shell contactGrid"><div><span className="kicker kickerLight">For parents</span><h2>Tell us what your child is curious about.</h2><p>We will propose a first-project direction and explain the format. Contact details must belong to an adult.</p><ContactButtons fallbackHref="/en/start" locale="en"/></div><div className="contactOnlyCard"><span className="cardMeta">Adult contact</span><h3>Short brief, no child contact data</h3><p>Age, interests, goal and online / Phuket format are enough. The child’s phone or email is not needed.</p><Link className="button buttonPrimary buttonWide" href="/en/start">What to send →</Link></div></div></section>
  </main><Footer locale="en"/></>;
}
