"use client";
import { useState } from "react";

type Locale="ru"|"en"; type Key="knowledge"|"documents"|"routing"|"decision";
type Scenario={label:string;title:string;signal:string;scope:string;ai:string;human:string;success:string;stop:string;artifact:string};
const scenarios:Record<Locale,Record<Key,Scenario>>={
ru:{
knowledge:{label:"Knowledge",title:"Internal knowledge triage",signal:"SOURCE-BOUND",scope:"Повторяемый поиск по разрешённой базе знаний, где ответ обязан опираться на конкретные источники.",ai:"Находит кандидатов, сравнивает фрагменты, собирает черновой ответ и отмечает неопределённость.",human:"Проверяет первоисточник, доступ к данным и принимает ответ перед использованием в работе.",success:"Заранее согласованный порог reviewer acceptance и времени на подготовку source-backed ответа.",stop:"Источники не покрывают вопрос, права доступа неясны или проверка занимает не меньше времени, чем текущий процесс.",artifact:"Workflow spec + source rules + test set + fallback."},
documents:{label:"Documents",title:"Document → decision memo",signal:"REVIEWABLE",scope:"Повторяемые документы, из которых команда регулярно извлекает факты, риски, вопросы и черновой memo.",ai:"Извлекает структуру, предлагает сравнение, формирует draft и показывает места, требующие проверки.",human:"Сверяет цифры и формулировки с документом, корректирует judgement и владеет финальным memo.",success:"Согласованный quality rubric проходит human review без роста критичных исправлений.",stop:"Модель теряет важный контекст, создаёт неподтверждённые факты или документ нельзя безопасно использовать.",artifact:"Extraction schema + memo template + QA rubric + exception path."},
routing:{label:"Routing",title:"Task / document routing",signal:"MEASURABLE",scope:"Повторяемый входящий поток, где категории, ответственные и исключения можно описать заранее.",ai:"Классифицирует, предлагает маршрут и помечает низкую уверенность или неизвестный тип.",human:"Проверяет спорные случаи, владеет правилами эскалации и меняет taxonomy при drift.",success:"Заранее заданные acceptance criteria на тестовом наборе и понятная доля случаев, уходящих на human review.",stop:"Категории нестабильны, цена неверного маршрута слишком высока или нет owner для исключений.",artifact:"Taxonomy + router prototype + test set + escalation rules."},
decision:{label:"Decision",title:"Decision preparation",signal:"HUMAN-OWNED",scope:"Решение остаётся за человеком, а AI помогает собрать evidence, варианты, trade-offs и вопросы.",ai:"Структурирует evidence, ищет противоречия, предлагает альтернативы и делает assumptions видимыми.",human:"Проверяет источники, задаёт веса рисков и принимает решение. AI не получает право действовать самостоятельно.",success:"Decision brief становится проверяемым: источники, допущения, риски и следующий шаг видимы до решения.",stop:"Нельзя проверить evidence, stakes требуют иной governance или команда пытается передать модели ответственность за решение.",artifact:"Decision brief + evidence map + assumptions + human sign-off gate."}},
en:{
knowledge:{label:"Knowledge",title:"Internal knowledge triage",signal:"SOURCE-BOUND",scope:"Repeatable search across an approved knowledge base where every useful answer must map back to concrete sources.",ai:"Finds candidate evidence, compares passages, drafts an answer and surfaces uncertainty.",human:"Checks the primary source, data access and approves the answer before operational use.",success:"A pre-agreed reviewer-acceptance and response-time threshold for source-backed answers.",stop:"Sources do not cover the question, access rights are unclear or review takes as long as the current process.",artifact:"Workflow spec + source rules + test set + fallback."},
documents:{label:"Documents",title:"Document → decision memo",signal:"REVIEWABLE",scope:"Recurring documents from which a team extracts facts, risks, questions and a draft memo.",ai:"Extracts structure, proposes comparisons, drafts the memo and flags points requiring verification.",human:"Checks numbers and wording against the document, adjusts judgement and owns the final memo.",success:"A pre-agreed quality rubric passes human review without increasing critical corrections.",stop:"Important context is lost, unsupported facts appear or the document cannot be used safely.",artifact:"Extraction schema + memo template + QA rubric + exception path."},
routing:{label:"Routing",title:"Task / document routing",signal:"MEASURABLE",scope:"A recurring inbound stream where categories, owners and exceptions can be defined in advance.",ai:"Classifies, proposes a route and flags low-confidence or unknown cases.",human:"Reviews ambiguous cases, owns escalation rules and updates taxonomy when drift appears.",success:"Pre-defined acceptance criteria on a test set plus a visible share of cases routed to human review.",stop:"Categories are unstable, the cost of a wrong route is too high or exceptions have no accountable owner.",artifact:"Taxonomy + router prototype + test set + escalation rules."},
decision:{label:"Decision",title:"Decision preparation",signal:"HUMAN-OWNED",scope:"The decision stays with a person while AI helps assemble evidence, options, trade-offs and questions.",ai:"Structures evidence, finds contradictions, explores alternatives and makes assumptions visible.",human:"Checks sources, weighs risk and makes the decision. AI receives no autonomous authority to act.",success:"The decision brief becomes reviewable: sources, assumptions, risks and the next action are visible before judgement.",stop:"Evidence cannot be verified, stakes require different governance or the team tries to transfer accountability to the model.",artifact:"Decision brief + evidence map + assumptions + human sign-off gate."}}
};
const keys:Key[]=["knowledge","documents","routing","decision"];
export function PilotSimulator({locale="ru"}:{locale?:Locale}){const [active,setActive]=useState<Key>("knowledge"),s=scenarios[locale][active],t=locale==="ru"?{scope:"Candidate scope",ai:"AI role",human:"Human checkpoint",success:"Success signal",stop:"Stop condition",artifact:"Pilot artifact",local:"Локальная демонстрация · данные не отправляются"}:{scope:"Candidate scope",ai:"AI role",human:"Human checkpoint",success:"Success signal",stop:"Stop condition",artifact:"Pilot artifact",local:"Local demo · no data is sent"};return <div className="proofLab" data-pilot-simulator><div className="proofLabTabs" role="group" aria-label={locale==="ru"?"Выберите тип бизнес-процесса":"Choose a business process type"}>{keys.map(k=><button type="button" key={k} className={`proofLabTab ${active===k?"isActive":""}`} aria-pressed={active===k} onClick={()=>setActive(k)} data-pilot-key={k}><span>{scenarios[locale][k].label}</span></button>)}</div><div className="proofLabStage" aria-live="polite"><div className="proofLabSignal"><i/>{t.local}</div><div className="proofLabTitleRow"><div><span>PILOT / 0{keys.indexOf(active)+1}</span><h2>{s.title}</h2></div><strong>{s.signal}</strong></div><div className="projectAnatomy"><p><span>01</span><b>{t.scope}</b><em>{s.scope}</em></p><p><span>02</span><b>{t.ai}</b><em>{s.ai}</em></p><p><span>03</span><b>{t.human}</b><em>{s.human}</em></p><p><span>04</span><b>{t.success}</b><em>{s.success}</em></p><p><span>05</span><b>{t.stop}</b><em>{s.stop}</em></p><p><span>06</span><b>{t.artifact}</b><em>{s.artifact}</em></p></div></div></div>}
