"use client";
import { useState } from "react";
type Locale="ru"|"en";type Key="adult"|"kids"|"teens"|"business";type Path={label:string;signal:string;think:string;build:string;verify:string;ship:string};
const DATA:Record<Locale,Record<Key,Path>>={
ru:{
adult:{label:"Adult",signal:"INDEPENDENT",think:"Контекст, спецификация, критерий полезного результата и работа с неопределённостью.",build:"Research workflows, документы, reusable patterns, automation и AI-assistant.",verify:"Источники, edge cases, hallucinations, privacy и ручные контрольные точки.",ship:"Рабочий процесс или инструмент + README + следующий самостоятельный цикл."},
kids:{label:"Kids 8–13",signal:"EXPLAINABLE",think:"Сильные вопросы, границы AI, цифровая безопасность и понимание, почему ответы надо проверять.",build:"Творчество, исследование, визуал, простая логика и собственный проект.",verify:"Факты, личный вклад, взрослый safety-контур и способность объяснить выбор.",ship:"Проект, который ребёнок может показать, объяснить и защитить своими словами."},
teens:{label:"Teens 14–18",signal:"PORTFOLIO-READY",think:"AI literacy, research framing, источники, product thinking и критерии качества.",build:"Code-thinking, automation, прототипирование и portfolio artifact.",verify:"Фактчекинг, failure modes, авторство, privacy и human review.",ship:"Законченный portfolio artifact + объяснимый личный вклад + repeatable process."},
business:{label:"Business",signal:"GOVERNED",think:"Карта процесса, owner, входы/выходы, права, data boundaries и success signal.",build:"Ограниченный pilot, workflow/prototype, routing и fallback-механика.",verify:"Human checkpoint, failure modes, stop condition и acceptance criteria.",ship:"Ship / Revise / Stop decision + handoff + operating rules + named owner."}},
en:{
adult:{label:"Adult",signal:"INDEPENDENT",think:"Context, specification, useful success criteria and working with uncertainty.",build:"Research workflows, documents, reusable patterns, automation and AI assistants.",verify:"Sources, edge cases, hallucinations, privacy and explicit human checkpoints.",ship:"A working process or tool + README + the next independent iteration."},
kids:{label:"Kids 8–13",signal:"EXPLAINABLE",think:"Strong questions, AI limits, digital safety and why answers require checking.",build:"Creative work, research, visuals, simple logic and an owned project.",verify:"Facts, personal contribution, adult safety layer and ability to explain choices.",ship:"A project the learner can show, explain and defend in their own words."},
teens:{label:"Teens 14–18",signal:"PORTFOLIO-READY",think:"AI literacy, research framing, sources, product thinking and quality criteria.",build:"Code-thinking, automation, prototyping and a portfolio artifact.",verify:"Fact checking, failure modes, authorship, privacy and human review.",ship:"A finished portfolio artifact + visible personal contribution + repeatable process."},
business:{label:"Business",signal:"GOVERNED",think:"Process map, owner, inputs/outputs, permissions, data boundaries and success signal.",build:"Bounded pilot, workflow/prototype, routing and fallback mechanics.",verify:"Human checkpoint, failure modes, stop condition and acceptance criteria.",ship:"Ship / Revise / Stop decision + handoff + operating rules + named owner."}}};
export function SkillGraph({locale="ru"}:{locale?:Locale}){const [active,setActive]=useState<Key>("adult"),d=DATA[locale],x=d[active],keys=Object.keys(d) as Key[];return <div className="proofLab" data-skill-graph><div className="proofLabTabs" role="group" aria-label={locale==="ru"?"Выберите траекторию навыков":"Choose a skill path"}>{keys.map(k=><button key={k} type="button" className={`proofLabTab ${active===k?"isActive":""}`} data-skill-key={k} aria-pressed={active===k} onClick={()=>setActive(k)}>{d[k].label}</button>)}</div><div className="proofLabStage" aria-live="polite"><div className="proofLabTitleRow"><div><span>SKILL PATH / {x.label.toUpperCase()}</span><h2>{locale==="ru"?"Навык как система":"Skill as a system"}</h2></div><strong>{x.signal}</strong></div><div className="proofFlow"><article><span>01 · THINK</span><b>Frame</b><p>{x.think}</p></article><article><span>02 · BUILD</span><b>Make</b><p>{x.build}</p></article><article><span>03 · VERIFY</span><b>Check</b><p>{x.verify}</p></article><article><span>04 · SHIP</span><b>Own</b><p>{x.ship}</p></article></div></div></div>}
