"use client";
import { useState } from "react";

type Locale="ru"|"en";type Key="research"|"product"|"automation"|"learning";
type Case={label:string;weak:string;define:string;ai:string;verify:string;ship:string;signal:string};
const DATA:Record<Locale,Record<Key,Case>>={
  ru:{
    research:{label:"Исследование",weak:"Изучи рынок и скажи, что нам делать.",define:"Решение: выбрать позиционирование; зафиксировать рынок, критерии сравнения и неизвестные.",ai:"Собрать варианты, источники, противоречия и карту доказательств.",verify:"Проверить качество источников, спорные допущения и альтернативные объяснения.",ship:"Краткое решение + карта источников. Остановка, если доказательства недостаточно для решения.",signal:"ПРИВЯЗАНО К ИСТОЧНИКУ"},
    product:{label:"Продукт",weak:"Сделай мне ИИ-продукт.",define:"Один пользователь, одна проблема, одна проверяемая задача.",ai:"Варианты, спецификация, UI/код и тестовая обвязка.",verify:"проверка человеком, известные ограничения, критерии приёмки и решение о выпуске.",ship:"Работающий прототип + проверки + передача. Остановка, если прототип не доказывает ценность.",signal:"ГОТОВО К ВЫПУСКУ"},
    automation:{label:"Автоматизация",weak:"Автоматизируй этот процесс.",define:"Описать триггер запуска, владельца, разрешения, входы, выходы и сценарии отказа.",ai:"Разбить рабочий процесс на этапы, преобразования, маршрутизацию и связующий код.",verify:"Пограничные случаи, откат, проверка человеком и наблюдаемая ошибка.",ship:"Рабочий процесс + запасной вариант + инструкции по работе. Остановка при неуправляемом сценарии отказа.",signal:"REPEATABLE"},
    learning:{label:"Обучение",weak:"Научи меня пользоваться ИИ.",define:"Определить навык, реальную задачу и результат, который ученик должен защитить сам.",ai:"Объяснять, давать варианты, упражнения и критиковать промежуточные решения.",verify:"Объяснение своими словами, проверка фактов, авторство и способность повторить процесс без подсказки.",ship:"Проект + объяснение + контрольный список. Остановка, если есть результат без понимания.",signal:"TRANSFERABLE"}
  },
  en:{
    research:{label:"Research",weak:"Research the market and tell us what to do.",define:"Decision: choose a position; define the market, comparison criteria and unknowns.",ai:"Collect alternatives, sources, contradictions and an evidence map.",verify:"Check source quality, disputed assumptions and alternative explanations.",ship:"Decision brief + source map. Stop if evidence is insufficient for a decision.",signal:"SOURCE-BOUND"},
    product:{label:"Product",weak:"Build me an AI product.",define:"Hypothesis: one user, one pain, one verifiable job-to-be-done.",ai:"Explore options and draft the spec, UI/code and test scaffolding.",verify:"Human QA, known limits, acceptance criteria and release decision.",ship:"Working prototype + tests + handoff. Stop if the prototype does not prove value.",signal:"SHIPPABLE"},
    automation:{label:"Automation",weak:"Automate this process.",define:"Define trigger, owner, permissions, inputs, outputs and failure modes.",ai:"Decompose the workflow, transformations, routing and glue code.",verify:"Edge cases, rollback, human checkpoint and observable failure.",ship:"Workflow + fallback + operating instructions. Stop on an uncontrolled failure mode.",signal:"REPEATABLE"},
    learning:{label:"Learning",weak:"Teach me how to use AI.",define:"Define the skill, real task and result the learner must be able to defend independently.",ai:"Explain, offer alternatives, create exercises and critique intermediate work.",verify:"Explain-back, fact checking, authorship and ability to repeat the process unaided.",ship:"Project + explanation + checklist. Stop if there is output without understanding.",signal:"TRANSFERABLE"}
  }
};
export function SystemChallenge({locale="ru"}:{locale?:Locale}){const [active,setActive]=useState<Key>("product"),d=DATA[locale],x=d[active],keys=Object.keys(d) as Key[];const l=locale==="ru"?{weak:"Слабый запрос",define:"ЗАДАЧА",ai:"СБОРКА / ИИ",verify:"ПРОВЕРКА",ship:"ЗАПУСК"}:{weak:"Weak request",define:"DEFINE",ai:"BUILD / AI",verify:"VERIFY",ship:"SHIP"};return <div className="proofLab" data-system-challenge><div className="proofLabTabs" role="group" aria-label={locale==="ru"?"Выберите ИИ-задачу":"Choose an AI task"}>{keys.map(k=><button key={k} type="button" className={`proofLabTab ${active===k?"isActive":""}`} data-challenge-key={k} aria-pressed={active===k} onClick={()=>setActive(k)}>{d[k].label}</button>)}</div><div className="proofLabStage" aria-live="polite"><div className="proofLabSignal"><i/>{l.weak}: <strong>{x.weak}</strong></div><div className="proofLabTitleRow"><div><span>{locale==="ru"?"РАЗМЫТО → СИСТЕМА":"VAGUE → SYSTEMIZED"}</span><h2>{x.label}</h2></div><strong>{x.signal}</strong></div><div className="proofFlow"><article><span>01 · {l.define}</span><b>{locale==="ru"?"Объём работ":"Scope"}</b><p>{x.define}</p></article><article><span>02 · {l.ai}</span><b>{locale==="ru"?"Роль ИИ":"AI role"}</b><p>{x.ai}</p></article><article><span>03 · {l.verify}</span><b>{locale==="ru"?"Проверка человеком":"Human gate"}</b><p>{x.verify}</p></article><article><span>04 · {l.ship}</span><b>{locale==="ru"?"Готовый результат / остановка":"Artifact / stop"}</b><p>{x.ship}</p></article></div></div></div>}
