"use client";
import { useState } from "react";

type Locale="ru"|"en";type Key="research"|"product"|"automation"|"learning";
type Case={label:string;weak:string;define:string;ai:string;verify:string;ship:string;signal:string};
const DATA:Record<Locale,Record<Key,Case>>={
  ru:{
    research:{label:"Research",weak:"Изучи рынок и скажи, что нам делать.",define:"Решение: выбрать позиционирование; зафиксировать рынок, критерии сравнения и неизвестные.",ai:"Собрать варианты, источники, противоречия и evidence map.",verify:"Проверить качество источников, спорные допущения и альтернативные объяснения.",ship:"Decision brief + source map. Stop, если evidence недостаточно для решения.",signal:"SOURCE-BOUND"},
    product:{label:"Product",weak:"Сделай мне AI-продукт.",define:"Гипотеза: один пользователь, одна боль, один проверяемый job-to-be-done.",ai:"Предложить варианты, спецификацию, UI/code и test scaffolding.",verify:"Human QA, known limits, acceptance criteria и release decision.",ship:"Working prototype + tests + handoff. Stop, если prototype не доказывает ценность.",signal:"SHIPPABLE"},
    automation:{label:"Automation",weak:"Автоматизируй этот процесс.",define:"Описать trigger, owner, permissions, входы, выходы и failure modes.",ai:"Декомпозировать workflow, transformations, routing и glue-code.",verify:"Edge cases, rollback, human checkpoint и наблюдаемая ошибка.",ship:"Workflow + fallback + operating instructions. Stop при неуправляемом failure mode.",signal:"REPEATABLE"},
    learning:{label:"Learning",weak:"Научи меня пользоваться AI.",define:"Определить навык, реальную задачу и результат, который ученик должен защитить сам.",ai:"Объяснять, давать варианты, упражнения и критиковать промежуточные решения.",verify:"Explain-back, фактчекинг, авторство и способность повторить процесс без подсказки.",ship:"Project + explanation + checklist. Stop, если есть результат без понимания.",signal:"TRANSFERABLE"}
  },
  en:{
    research:{label:"Research",weak:"Research the market and tell us what to do.",define:"Decision: choose a position; define the market, comparison criteria and unknowns.",ai:"Collect alternatives, sources, contradictions and an evidence map.",verify:"Check source quality, disputed assumptions and alternative explanations.",ship:"Decision brief + source map. Stop if evidence is insufficient for a decision.",signal:"SOURCE-BOUND"},
    product:{label:"Product",weak:"Build me an AI product.",define:"Hypothesis: one user, one pain, one verifiable job-to-be-done.",ai:"Explore options and draft the spec, UI/code and test scaffolding.",verify:"Human QA, known limits, acceptance criteria and release decision.",ship:"Working prototype + tests + handoff. Stop if the prototype does not prove value.",signal:"SHIPPABLE"},
    automation:{label:"Automation",weak:"Automate this process.",define:"Define trigger, owner, permissions, inputs, outputs and failure modes.",ai:"Decompose the workflow, transformations, routing and glue code.",verify:"Edge cases, rollback, human checkpoint and observable failure.",ship:"Workflow + fallback + operating instructions. Stop on an uncontrolled failure mode.",signal:"REPEATABLE"},
    learning:{label:"Learning",weak:"Teach me how to use AI.",define:"Define the skill, real task and result the learner must be able to defend independently.",ai:"Explain, offer alternatives, create exercises and critique intermediate work.",verify:"Explain-back, fact checking, authorship and ability to repeat the process unaided.",ship:"Project + explanation + checklist. Stop if there is output without understanding.",signal:"TRANSFERABLE"}
  }
};
export function SystemChallenge({locale="ru"}:{locale?:Locale}){const [active,setActive]=useState<Key>("product"),d=DATA[locale],x=d[active],keys=Object.keys(d) as Key[];const l=locale==="ru"?{weak:"Слабый запрос",define:"DEFINE",ai:"BUILD / AI",verify:"VERIFY",ship:"SHIP"}:{weak:"Weak request",define:"DEFINE",ai:"BUILD / AI",verify:"VERIFY",ship:"SHIP"};return <div className="proofLab" data-system-challenge><div className="proofLabTabs" role="group" aria-label={locale==="ru"?"Выберите AI-задачу":"Choose an AI task"}>{keys.map(k=><button key={k} type="button" className={`proofLabTab ${active===k?"isActive":""}`} data-challenge-key={k} aria-pressed={active===k} onClick={()=>setActive(k)}>{d[k].label}</button>)}</div><div className="proofLabStage" aria-live="polite"><div className="proofLabSignal"><i/>{l.weak}: <strong>{x.weak}</strong></div><div className="proofLabTitleRow"><div><span>VAGUE → SYSTEMIZED</span><h2>{x.label}</h2></div><strong>{x.signal}</strong></div><div className="proofFlow"><article><span>01 · {l.define}</span><b>Scope</b><p>{x.define}</p></article><article><span>02 · {l.ai}</span><b>AI role</b><p>{x.ai}</p></article><article><span>03 · {l.verify}</span><b>Human gate</b><p>{x.verify}</p></article><article><span>04 · {l.ship}</span><b>Artifact / stop</b><p>{x.ship}</p></article></div></div></div>}
