import Link from "next/link";
import { commercialFacts, localizedName, sessionDurationMinutes, type WorkshopLocale } from "@/lib/commercial";
import { WorkshopShell } from "./WorkshopShell";
import styles from "./WorkshopShell.module.css";

export function WorkshopPricing({ locale = "ru" }: { locale?: WorkshopLocale }) {
  const en = locale === "en";
  const p = (ru: string) => en ? `/en${ru}` : ru;
  const groups = [
    [en ? "Adults" : "Взрослые", commercialFacts.tracks.adult],
    [en ? "Kids 8–13" : "Дети 8–13", commercialFacts.tracks.kids],
    [en ? "Teens 14–18" : "Подростки 14–18", commercialFacts.tracks.teens],
  ] as const;
  const business = commercialFacts.business;
  const recurring = commercialFacts.recurring;
  const pair = commercialFacts.pair;
  return (
    <WorkshopShell locale={locale} alternateHref={en ? "/pricing" : "/en/pricing"}>
      <main id="main">
        <section className={styles.pricingHero}><span>PRICING · USD · 1:1</span><h1>{en ? <>Know the price.<br/><em>Define the scope.</em></> : <>Знайте цену.<br/><em>Фиксируйте scope.</em></>}</h1><p>{en ? `Every session is ${sessionDurationMinutes} minutes. There is no checkout: final scope, schedule, payment and rescheduling terms are confirmed in writing.` : `Каждая сессия — ${sessionDurationMinutes} минут. Checkout нет: финальный scope, расписание, оплата и переносы подтверждаются письменно.`}</p><Link className="workshopButton workshopButtonPrimary" href={p("/start")}>{en ? "Choose a route →" : "Подобрать маршрут →"}</Link></section>
        <section className={styles.section}><div className={styles.sectionHead}><span>{en ? "LOW-RISK START" : "КОРОТКИЙ СТАРТ"}</span><h2>{en ? "Diagnose before committing to a package." : "Сначала диагностика, затем пакет."}</h2></div><article className={styles.diagnostic}><div><span>{localizedName(commercialFacts.diagnostic, locale)}</span><strong>{commercialFacts.diagnostic.price}</strong><b>{sessionDurationMinutes} {en ? "minutes" : "минут"}</b></div><p>{en ? commercialFacts.diagnostic.credit_en : commercialFacts.diagnostic.credit_ru}</p><Link className="workshopButton workshopButtonSecondary" href={p("/start")}>{en ? "Book diagnostic →" : "Обсудить диагностику →"}</Link></article></section>
        {groups.map(([name, plans], groupIndex) => <section className={`${styles.section} ${groupIndex === 1 ? styles.panelSection : ""}`} key={name}><div className={styles.sectionHead}><span>{name}</span><h2>{en ? "Choose the depth, not a mystery price." : "Выбирайте глубину, а не неизвестную цену."}</h2></div><div className={styles.priceGrid}>{plans.map(plan => <article className={styles.priceCard} key={plan.id}><span>{plan.name}</span><strong>{plan.price}</strong><b>{en ? plan.sessions_en : plan.sessions_ru}</b><p>{en ? plan.summary_en : plan.summary_ru}</p></article>)}</div></section>)}
        <section className={`${styles.section} ${styles.paper}`}><div className={styles.sectionHead}><span>{commercialFacts.family.name}</span><h2>{commercialFacts.family.price}</h2></div><div className={styles.familyRow}><p><strong>{en ? commercialFacts.family.sessions_en : commercialFacts.family.sessions_ru}</strong><br/>{en ? commercialFacts.family.summary_en : commercialFacts.family.summary_ru}</p><Link className="workshopButton workshopButtonDark" href={p("/start")}>{en ? "Discuss Family →" : "Обсудить Family →"}</Link></div></section>
        <section className={styles.darkBand}><div><span>{en ? "PAIR FORMAT" : "ПАРНЫЙ ФОРМАТ"}</span><h2>{en ? `${pair.multiplier}× the individual package price.` : `${String(pair.multiplier).replace(".", ",")}× цены индивидуального пакета.`}</h2><p>{en ? `Each participant pays ${pair.participant_discount_percent}% less than the individual package price.` : `Каждый участник платит на ${pair.participant_discount_percent}% меньше индивидуальной цены пакета.`}</p></div><Link className="workshopButton workshopButtonLight" href={p("/start")}>{en ? "Ask about a pair →" : "Спросить про пару →"}</Link></section>
        <section className={styles.section}><div className={styles.sectionHead}><span>{en ? "BUSINESS" : "БИЗНЕС"}</span><h2>{en ? "Three bounded ways to start." : "Три ограниченных формата старта."}</h2></div><div className={styles.priceGrid}><article className={styles.priceCard}><span>{localizedName(business.workflow_audit, locale)}</span><strong>{business.workflow_audit.price}</strong><b>{en ? "fixed scope" : "фиксированный scope"}</b><p>{en ? "Map one workflow, risks and a decision-ready next step." : "Карта одного процесса, риски и следующий шаг."}</p></article><article className={styles.priceCard}><span>{localizedName(business.team_training, locale)}</span><strong>{en ? `from ${business.team_training.price_from_per_session}` : `от ${business.team_training.price_from_per_session}`}</strong><b>{en ? `up to ${business.team_training.max_people} people · minimum ${business.team_training.min_sessions} sessions` : `до ${business.team_training.max_people} человек · минимум ${business.team_training.min_sessions} занятия`}</b><p>{en ? `Minimum engagement from ${business.team_training.total_from}.` : `Минимальный объём — от ${business.team_training.total_from}.`}</p></article><article className={styles.priceCard}><span>{localizedName(business.implementation_pilot, locale)}</span><strong>{en ? `from ${business.implementation_pilot.price_from}` : `от ${business.implementation_pilot.price_from}`}</strong><b>{en ? `scope cap ${business.implementation_pilot.scope_cap_hours} hours` : `потолок scope ${business.implementation_pilot.scope_cap_hours} часов`}</b><p>Prototype · QA · ownership · handoff.</p></article></div></section>
        <section className={`${styles.section} ${styles.panelSection}`}><div className={styles.sectionHead}><span>{en ? "AFTER LAUNCH" : "ПОСЛЕ ЗАПУСКА"}</span><h2>{en ? "Recurring support remains bounded." : "Сопровождение остаётся ограниченным."}</h2></div><div className={styles.priceGrid}><article className={styles.priceCard}><span>{localizedName(recurring.operating_support, locale)}</span><strong>{recurring.operating_support.price_monthly}{en ? "/month" : "/мес"}</strong><b>{recurring.operating_support.hours} {en ? "hours" : "часа"}</b></article><article className={styles.priceCard}><span>{localizedName(recurring.operating_partner, locale)}</span><strong>{recurring.operating_partner.price_monthly}{en ? "/month" : "/мес"}</strong><b>{recurring.operating_partner.hours} {en ? "hours" : "часов"}</b></article><article className={styles.priceCard}><span>{localizedName(recurring.office_hours, locale)}</span><strong>{recurring.office_hours.price_monthly}{en ? "/month" : "/мес"}</strong><b>{recurring.office_hours.sessions} {en ? "sessions" : "сессии"}</b></article></div></section>
        <section className={`${styles.section} ${styles.paper}`}><div className={styles.sectionHead}><span>{en ? "BEFORE PAYMENT" : "ДО ОПЛАТЫ"}</span><h2>{en ? "Commercial terms are confirmed in writing." : "Коммерческие условия фиксируются письменно."}</h2></div><p className={styles.longCopy}>{en ? "Website prices describe the stated packages and testing offers. Final scope, currency and payment method, schedule, rescheduling, cancellation and refund terms are confirmed before payment. Agreed written individual terms take priority if they differ from the site." : "Цены на сайте описывают указанные пакеты и тестируемые офферы. Финальный scope, валюта и способ оплаты, расписание, переносы, отмена и возврат подтверждаются до оплаты. При расхождении приоритет имеют согласованные письменные условия."}</p><div className={styles.sectionActions}><Link href={p("/terms")}>{en ? "Learning terms →" : "Условия обучения →"}</Link><Link href={p("/start#business-brief")}>Business brief →</Link></div></section>
      </main>
    </WorkshopShell>
  );
}
