#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import process from 'node:process';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const js=fs.readFileSync(path.join(root,'deploy/live/start-brief.js'),'utf8');
class E{constructor(value=''){this.value=value;this.checked=false;this.required=false;this.hidden=false;this.disabled=false;this.textContent='';this.className='';this.listeners=new Map()}addEventListener(t,f){this.listeners.set(t,f)}async trigger(t){const f=this.listeners.get(t);if(f)await f({preventDefault(){}})}}
class Wrap extends E{constructor(input){super();this.input=input}querySelector(s){return s==='input[name="adultConfirmation"]'?this.input:null}}
class Form{constructor(locale,audience='adult'){this.locale=locale;this.listeners=new Map();this.elements={audience:new E(audience)};this.adult=new E();this.adultWrap=new Wrap(this.adult);this.message=new E();this.submitButton=new E();this.privacy=new E();this.privacy.checked=true;this.data={name:'Test Adult',contact:'adult@example.net',goal:'Test goal',program:'',sourcePath:locale==='en'?'/en/start':'/start',website:''}}addEventListener(t,f){this.listeners.set(t,f)}querySelector(s){if(s==='[data-adult-confirmation]')return this.adultWrap;if(s==='[data-lead-message]')return this.message;if(s==='button[type="submit"]')return this.submitButton;return null}reset(){this.elements.audience.value='adult';this.adult.checked=false;this.privacy.checked=false}async submit(){await this.listeners.get('submit')?.({preventDefault(){}})}}
class FD{constructor(form){this.form=form}*entries(){const f=this.form;for(const [k,v] of Object.entries({locale:f.locale,program:f.data.program,sourcePath:f.data.sourcePath,name:f.data.name,audience:f.elements.audience.value,contact:f.data.contact,goal:f.data.goal,website:f.data.website}))yield[k,v];if(f.privacy.checked)yield['privacyConsent','yes'];if(f.adult.checked)yield['adultConfirmation','yes']}}
async function run({locale='en',audience='adult',adult=false,responseOk=true}){const form=new Form(locale,audience);form.adult.checked=adult;const calls=[];const document={documentElement:{lang:locale},referrer:'',body:{appendChild(){}},querySelector(s){return s==='#application-form'?form:null},querySelectorAll(){return[]},createElement(){return new E()},execCommand(){return true}};const navigator={clipboard:{async writeText(){}}};const location={origin:'https://aiskillab.work',pathname:locale==='en'?'/en/start':'/start'};const fetch=async(url,opts)=>{calls.push({url,opts});return responseOk?{ok:true,async json(){return{ok:true,requestId:'test'}}}:{ok:false,async json(){return{ok:false,error:'Request rejected'}}}};const ctx={document,navigator,location,URL,FormData:FD,fetch,setTimeout(){return 1},clearTimeout(){},console};ctx.window=ctx;vm.runInNewContext(js,ctx,{filename:'start-brief.js',timeout:1000});if(calls.length!==0)throw new Error('network call during load');return{form,calls,submit:()=>form.submit()}}
let checks=0;const adult=await run({locale:'en'});if(!adult.form.adultWrap.hidden||adult.form.adult.required)throw new Error('adult confirmation must be dormant for adult');checks+=2;await adult.submit();if(adult.calls.length!==1)throw new Error('adult submit count');const a=adult.calls[0];if(a.url!=='/api/lead'||a.opts.method!=='POST'||a.opts.headers['Content-Type']!=='application/json')throw new Error('adult request route/method/header');const ab=JSON.parse(a.opts.body);for(const [k,v] of Object.entries({locale:'en',sourcePath:'/en/start',audience:'adult',privacyConsent:'yes'}))if(ab[k]!==v)throw new Error(`adult body ${k}`);if('adultConfirmation'in ab)throw new Error('adult confirmation leaked into adult body');if(!adult.form.message.textContent.includes('Application sent'))throw new Error('adult success feedback');checks+=7;
const parent=await run({locale:'ru',audience:'parent',adult:true});if(parent.form.adultWrap.hidden||!parent.form.adult.required)throw new Error('parent adult confirmation not required');checks+=2;await parent.submit();if(parent.calls.length!==1)throw new Error('parent submit count');const pb=JSON.parse(parent.calls[0].opts.body);for(const [k,v] of Object.entries({locale:'ru',sourcePath:'/start',audience:'parent',privacyConsent:'yes',adultConfirmation:'yes'}))if(pb[k]!==v)throw new Error(`parent body ${k}`);if(!parent.form.message.textContent.includes('Заявка отправлена'))throw new Error('parent success feedback');checks+=7;
const fail=await run({locale:'en',responseOk:false});await fail.submit();if(fail.calls.length!==1)throw new Error('failure submit count');if(!fail.form.message.textContent.includes('Could not send the application'))throw new Error('safe failure feedback');if(fail.form.submitButton.disabled)throw new Error('submit stayed disabled');checks+=3;
console.log(`public_form_runtime_checks=${checks} cases=3 fetch_calls=${adult.calls.length+parent.calls.length+fail.calls.length}`);console.log('PUBLIC_FORM_RUNTIME_PASS');
