#!/usr/bin/env python3
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
errors = []
checks = 0

proof_surfaces = [
    ("app/proof/page.tsx", False, "source RU"),
    ("app/en/proof/page.tsx", True, "source EN"),
    ("deploy/live/proof.html", False, "static RU"),
    ("deploy/live/en/proof.html", True, "static EN"),
]
common = [
    "SITE AS PROOF",
    "DEFINE",
    "BUILD",
    "VERIFY",
    "SHIP",
    "HASHED CSP",
    "BYTE-EXACT",
    "Release manifest",
]
for rel, en, label in proof_surfaces:
    text = (ROOT / rel).read_text(encoding="utf-8")
    for marker in common:
        checks += 1
        if marker not in text:
            errors.append(f"{label}: missing {marker}")
    honesty = (
        ["not a hidden AI call", "not a data-collection form", "What this site does", "not</em> prove"]
        if en
        else ["не скрытый AI-вызов", "не сбор персональных данных", "Что этот сайт", "не</em> доказывает"]
    )
    for marker in honesty:
        checks += 1
        if marker not in text:
            errors.append(f"{label}: missing honesty {marker}")
    for forbidden in ["live AI model", "real-time AI model", "powered by GPT", "generated by ChatGPT"]:
        checks += 1
        if forbidden.lower() in text.lower():
            errors.append(f"{label}: forbidden {forbidden}")

mounts = {
    "app/page.tsx": '<R77CommercialHome locale="ru" />',
    "app/en/page.tsx": '<R77CommercialHome locale="en" />',
}
for rel, marker in mounts.items():
    checks += 1
    if marker not in (ROOT / rel).read_text(encoding="utf-8"):
        errors.append(f"{rel}: R77 home mount missing")

home_component = (ROOT / "components/R77CommercialHome.tsx").read_text(encoding="utf-8")
for marker in [
    'p("/proof")',
    "ПРОВЕРЯЕМЫЙ ПОДХОД",
    "VERIFIABLE PRACTICE",
    "Открыть Proof Lab →",
    "Open Proof Lab →",
    "Proof stays — after the offer, not instead of it.",
]:
    checks += 1
    if marker not in home_component:
        errors.append(f"components/R77CommercialHome.tsx: missing {marker!r}")

home_static = {
    "deploy/live/index.html": ['href="/proof"', "ПРОВЕРЯЕМЫЙ ПОДХОД", "Открыть Proof Lab →", "Proof остаётся"],
    "deploy/live/en.html": ['href="/en/proof"', "VERIFIABLE PRACTICE", "Open Proof Lab →", "Proof stays"],
}
for rel, markers in home_static.items():
    text = (ROOT / rel).read_text(encoding="utf-8")
    for marker in markers:
        checks += 1
        if marker not in text:
            errors.append(f"{rel}: missing proof discoverability {marker!r}")

print(f"proof_route_checks={checks} proof_surfaces={len(proof_surfaces)} home_surfaces=5")
if errors:
    for error in errors:
        print("FAIL:", error)
    sys.exit(1)
print("PROOF_ROUTE_PARITY_PASS")
