#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path'; import vm from 'node:vm'; import process from 'node:process';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
class CL{constructor(el){this.el=el}toggle(name,on){const s=new Set((this.el.className||'').split(/\s+/).filter(Boolean));on?s.add(name):s.delete(name);this.el.className=[...s].join(' ')}}
class E{constructor({filter='',tags='',word=''}={}){this.dataset={};if(filter)this.dataset.projectFilter=filter;if(tags)this.dataset.projectTags=tags;if(word)this.dataset.word=word;this.attrs={};this.listeners={};this.hidden=false;this.textContent='';this.className=filter==='all'?'projectFilter isActive':'projectFilter';this.classList=new CL(this)}addEventListener(t,f){this.listeners[t]=f}setAttribute(k,v){this.attrs[k]=String(v)}getAttribute(k){return this.attrs[k]??null}trigger(){if(!this.listeners.click)throw new Error('listener missing');return this.listeners.click.call(this,{target:this})}}
function extract(file){const h=fs.readFileSync(file,'utf8');const scripts=[...h.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);const js=scripts.find(x=>x.includes("[data-project-filter]")&&x.includes("[data-project-tags]"));if(!js)throw new Error(`Project Studio script missing ${file}`);return js}
const projectTags=['research','create','build create','research build','build automate','build create','research automate','automate build','automate'];
function run(rel,en){const filters=['all','research','create','build','automate'];const buttons=filters.map(f=>new E({filter:f}));const cards=projectTags.map(tags=>new E({tags}));const status=new E({word:en?'projects shown':'проектов показано'});const document={querySelectorAll:s=>s==='[data-project-filter]'?buttons:s==='[data-project-tags]'?cards:[],getElementById:id=>id==='project-filter-status'?status:null};const ctx={document,console};ctx.window=ctx;vm.runInNewContext(extract(path.join(root,rel)),ctx,{timeout:1000});let checks=0;const visible=()=>cards.filter(c=>!c.hidden).length;const assert=(cond,msg)=>{checks++;if(!cond)throw new Error(`${rel}: ${msg}`)};assert(visible()===9,'default all');assert(status.textContent.startsWith('9 / 9'),'default status');const expected={research:3,create:3,build:5,automate:4,all:9};for(const f of ['research','create','build','automate','all']){buttons.find(b=>b.dataset.projectFilter===f).trigger();assert(visible()===expected[f],`${f} count`);assert(buttons.find(b=>b.dataset.projectFilter===f).getAttribute('aria-pressed')==='true',`${f} pressed`);assert(status.textContent.startsWith(`${expected[f]} / 9`),`${f} status`)}assert(cards.length===9,'all cards remain in DOM');return checks}
try{const a=run('deploy/live/projects.html',false),b=run('deploy/live/en/projects.html',true);console.log(`project_studio_runtime_checks=${a+b} pages=2`);console.log('PROJECT_STUDIO_RUNTIME_PASS')}catch(e){console.error('FAIL:',e?.stack||e);process.exit(1)}
