#!/usr/bin/env python3
from pathlib import Path
import json
from source_paths import source_path
import sys

ROOT = Path(__file__).resolve().parents[1]
E32 = json.loads((ROOT / "deploy/live/_release.json").read_text(encoding="utf-8")).get("release_id") == "E3_2_RU_GLOSSARY_R1"
errors = []
checks = 0

proof_surfaces = [
    ("app/proof/page.tsx", False, "source RU"),
    ("app/en/proof/page.tsx", True, "source EN"),
    ("deploy/live/proof.html", False, "static RU"),
    ("deploy/live/en/proof.html", True, "static EN"),
]
common = [
    "SITE AS PROOF",
    "DEFINE",
    "BUILD",
    "VERIFY",
    "SHIP",
    "HASHED CSP",
    "BYTE-EXACT",
    "Release manifest",
]
E32_PROOF_COMMON = {
 "SITE AS PROOF":"САЙТ КАК ДОКАЗАТЕЛЬСТВО",
 "Release manifest":"МАНИФЕСТ ВЫПУСКА",
}
for rel, en, label in proof_surfaces:
    text = source_path(ROOT, rel).read_text(encoding="utf-8")
    for marker in common:
        checks += 1
        required = E32_PROOF_COMMON.get(marker,marker) if E32 and not en else marker
        if required not in text:
            errors.append(f"{label}: missing {required}")
    honesty = (
        ["not a hidden AI call", "not a data-collection form", "What this site does", "not</em> prove"]
        if en
        else ["не скрытый AI-вызов", "не сбор персональных данных", "Что этот сайт", "не</em> доказывает"]
    )
    if E32 and not en:
        honesty = ["без скрытых вызовов ИИ","сбора персональных данных","Что этот сайт","не</em> доказывает"]
    for marker in honesty:
        checks += 1
        if marker not in text:
            errors.append(f"{label}: missing honesty {marker}")
    for forbidden in ["live AI model", "real-time AI model", "powered by GPT", "generated by ChatGPT"]:
        checks += 1
        if forbidden.lower() in text.lower():
            errors.append(f"{label}: forbidden {forbidden}")
    privacy = (
        "The public site uses Vercel Web Analytics for anonymized visit statistics; it uses no cookies or advertising trackers. Forms exist on /start and /matcher: matcher calls /api/route only on button press, and sends its brief to /api/lead only with consent."
        if en
        else "Публичный сайт использует Vercel Web Analytics для обезличенной статистики посещений; cookies и рекламные trackers не используются. Формы есть на /start и /matcher: matcher вызывает /api/route только по кнопке, а brief отправляет в /api/lead только по согласию."
    )
    checks += 3
    if privacy not in text:
        errors.append(f"{label}: current client-privacy fact missing")
    if "<b>public_forms</b><strong>2</strong>" not in text:
        errors.append(f"{label}: public_forms must equal 2")
    if "<b>public_forms</b><strong>0</strong>" in text or "<b>public_forms</b><strong>1</strong>" in text:
        errors.append(f"{label}: stale public_forms count")
    if "<b>ad_trackers</b><strong>0</strong>" not in text or "<b>trackers</b><strong>0</strong>" in text:
        errors.append(f"{label}: analytics/ad-tracker truth drift")

mounts = {
    "app/page.tsx": '<WorkshopHome locale="ru" />',
    "app/en/page.tsx": '<WorkshopHome locale="en" />',
}
for rel, marker in mounts.items():
    checks += 1
    if marker not in source_path(ROOT, rel).read_text(encoding="utf-8"):
        errors.append(f"{rel}: Workshop home mount missing")

home_component = (ROOT / "components/workshop/WorkshopHome.tsx").read_text(encoding="utf-8")
for marker in [
    'p("/proof")',
    "ПРОВЕРЯЕМЫЙ ПОДХОД",
    "VERIFIABLE PRACTICE",
    "Открыть Proof Lab →",
    "Open Proof Lab →",
    "Proof stays — after the offer, not instead of it.",
]:
    checks += 1
    required = "Открыть примеры и проверку →" if E32 and marker == "Открыть Proof Lab →" else marker
    if required not in home_component:
        errors.append(f"components/workshop/WorkshopHome.tsx: missing {required!r}")

home_static = {
    "deploy/live/index.html": ['href="/proof"', "ПРОВЕРЯЕМЫЙ ПОДХОД", "Открыть Proof Lab →", "Proof остаётся"],
    "deploy/live/en.html": ['href="/en/proof"', "VERIFIABLE PRACTICE", "Open Proof Lab →", "Proof stays"],
}
for rel, markers in home_static.items():
    text = source_path(ROOT, rel).read_text(encoding="utf-8")
    if E32 and rel == "deploy/live/index.html":
        markers = [{"Proof остаётся":"Проверка остаётся","Открыть Proof Lab →":"Открыть примеры и проверку →"}.get(x,x) for x in markers]
    for marker in markers:
        checks += 1
        if marker not in text:
            errors.append(f"{rel}: missing proof discoverability {marker!r}")

print(f"proof_route_checks={checks} proof_surfaces={len(proof_surfaces)} home_surfaces=5")
if errors:
    for error in errors:
        print("FAIL:", error)
    sys.exit(1)
print("PROOF_ROUTE_PARITY_PASS")
